control_tower_task_path: "https://github.com/carrier-io/control_tower/releases/download/beta-1.0/control-tower.zip"
rabbit_queue_checker_task_path: "https://github.com/carrier-io/rabbit_queue_checker/releases/download/beta-1.0/rabbit_queue_checker.zip"
